<?php

namespace DreamCommerce\ShopAppstoreBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * BillingRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BillingRepository extends EntityRepository implements BillingRepositoryInterface
{
}
