<?php
/**
 * Created by PhpStorm.
 * User: eRIZ
 * Date: 2015-03-18
 * Time: 17:00
 */
namespace DreamCommerce\ShopAppstoreBundle\Model;


/**
 * BillingRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
interface BillingRepositoryInterface
{
}