<?php

namespace DreamCommerce\ShopAppstoreBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * ShopRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ShopRepository extends EntityRepository implements ShopRepositoryInterface
{
}
