<?php
/**
 * Created by PhpStorm.
 * User: eRIZ
 * Date: 2015-03-19
 * Time: 14:30
 */
namespace DreamCommerce\ShopAppstoreBundle\Model;


/**
 * SubscriptionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
interface SubscriptionRepositoryInterface
{
}