<?php

namespace DreamCommerce\ShopAppstoreBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository implements SubscriptionRepositoryInterface
{
}
