<?php
/**
 * Created by PhpStorm.
 * User: eRIZ
 * Date: 2015-03-19
 * Time: 14:31
 */
namespace DreamCommerce\ShopAppstoreBundle\Model;


/**
 * TokenRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
interface TokenRepositoryInterface
{
}