<?php

namespace DreamCommerce\ShopAppstoreBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * TokenRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TokenRepository extends EntityRepository implements TokenRepositoryInterface
{
}
