kind: pipeline
type: kubernetes
name: release_new_version

steps:
    -   name: push_to_nexus
        image: composer:2.1.12
        environment:
            NEXUS_USERNAME:
                from_secret: NEXUS_USERNAME
            NEXUS_PASSWORD:
                from_secret: NEXUS_PASSWORD
            NEXUS_URL:
                from_secret: NEXUS_URL
        commands:
            - composer global require elendev/nexus-composer-push
            - composer nexus-push --username=$$NEXUS_USERNAME --password=$$NEXUS_PASSWORD --url=$$NEXUS_URL ${DRONE_TAG##v}
        when:
            branch:
                - master
            event:
                - tag
